export const datakereta = [
    {
        id: 1,
        name: "Argo Wilis",
        class: "Eksekutif(H)",
        start_time: "05.00",
        arival_time: "10.05",
        start_date: "21 Februari 2020" ,
        end_date: "21 Februari 2020",
        start_station: "Gambir",
        start_station_town: "Jakarta(GMR)",
        destination_station: "Surabaya",
        destination_station_town: "Surabaya(SBY)",
        duration: "5j 05m",
        price: "Rp.250.000",
    },
    {
        id: 2,
        name: "Wilis Argo",
        class: "Ekonomi(Q)",
        start_time: "05.00",
        arival_time: "10.05",
        start_date: "21 Februari 2020",
        end_date: "21 Februari 2020",
        start_station: "Gambir",
        start_station_town: "Jakarta(GMR)",
        destination_station: "Surabaya",
        destination_station_town: "Surabaya(SBY)",
        duration: "5j 05m",
        price: "Rp.100.000",
    },
    {
        id: 3,
        name: "Anjasmoro",
        class: "Ekonomi(Q)",
        start_time: "05.00",
        arival_time: "10.05",
        start_date: "21 Februari 2020",
        end_date: "21 Februari 2020",
        start_station: "Gambir",
        start_station_town: "Jakarta(GMR)",
        destination_station: "Surabaya",
        destination_station_town: "Surabaya(SBY)",
        duration: "5j 05m",
        price: "Rp.100.000"
    }
]